Repository colcon/colcon-core, pull requests merged in 2018-10, with the labels that each got.

#116 add descriptor for package dependencies
  colcon_core/dependency_descriptor.py
  colcon_core/package_descriptor.py
  test/spell_check.words
  test/test_dependency_descriptor.py
Labels: enhancement, review

#117 remove unused variable
  colcon_core/subprocess.py
Labels: review

#118 Update python package identification to use DependencyDescriptor
  .travis.yml
  appveyor.yml
  colcon_core/package_identification/python.py
  setup.cfg
  stdeb.cfg
  test/test_package_identification_python.py
Labels: enhancement, review

#120 Update python incompatible version algorithm to use tuple unpacking
  colcon_core/package_identification/python.py
Labels: review

#121 add desc order in changelog link
  setup.cfg
Labels: review

#122 Bug when setting a python executable and it is not used
  colcon_core/shell/template/prefix.bat.em
Labels: bug, review

#123 update code and flake8 arguments to pass with flake8 3.6.x / pycodestyle 2.4.x
  colcon_core/argument_parser/__init__.py
  colcon_core/command.py
  colcon_core/entry_point.py
  colcon_core/environment/__init__.py
  colcon_core/event_reactor.py
  colcon_core/executor/__init__.py
  colcon_core/executor/sequential.py
  colcon_core/logging.py
  colcon_core/package_augmentation/__init__.py
  colcon_core/package_discovery/__init__.py
  colcon_core/package_identification/__init__.py
  colcon_core/package_selection/__init__.py
  colcon_core/plugin_system.py
  colcon_core/shell/__init__.py
  colcon_core/shell/template/__init__.py
  colcon_core/subprocess.py
  colcon_core/task/__init__.py
  colcon_core/task/python/test/__init__.py
  colcon_core/verb/build.py
  test/test_flake8.py
Labels: review

#124 replace 'typeset' usage in sh with 'command'
  colcon_core/shell/template/package.sh.em
Labels: bug, review

#126 explicitly set log level of pydocstyle
  test/spell_check.words
  test/test_flake8.py
Labels: bug, review

#127 fix flake8 test logic
  test/test_flake8.py
Labels: bug, review

#125 switch to scspell3k
  .travis.yml
  appveyor.yml
  bin/colcon
  setup.cfg
  test/spell_check.words
  test/test_spell_check.py
Labels: bug, review

#128 handle multiline environment variables
  colcon_core/shell/__init__.py
  test/test_shell.py
Labels: bug, review
