Repository colcon/colcon-core, pull requests merged in 2019-10, with the labels that each got.

#241 add type 'set' for dsv files
  colcon_core/shell/dsv.py
  colcon_core/shell/template/hook_set_value.dsv.em
  colcon_core/shell/template/prefix_util.py.em
Labels: enhancement, review

#243 Clarify new pytest version requirement
  setup.cfg
Labels: bug

#244 always consider .dsv files, even when no shell specific script exists
  colcon_core/shell/template/prefix_util.py.em
Labels: bug, review

#246 avoid requiring tmp_path introduce in pytest 3.9.0
  setup.cfg
  test/test_build_python.py
Labels: review

#247 Add support for prepending multiple values to env variables from .dsv files
  colcon_core/shell/template/prefix_util.py.em
Labels: enhancement

#250 add dsv type set-if-unset
  colcon_core/shell/template/prefix_util.py.em
Labels: enhancement, review

#249 support more characters in environment variable names on Windows
  colcon_core/shell/__init__.py
Labels: bug, review

#251 check that no arguments are passed to the setup() function in setup.py
  colcon_core/package_identification/python.py
  test/test_package_identification_python.py
Labels: bug, review

#256 avoid repeated list comprehension
  colcon_core/package_descriptor.py
Labels: enhancement, review

#257 use a plain str where sufficient
  colcon_core/topological_order.py
Labels: enhancement, review

#254 Always prepend with a trailing separator
  colcon_core/shell/__init__.py
  colcon_core/shell/bat.py
  colcon_core/shell/sh.py
  colcon_core/shell/template/prefix_util.py.em
Labels: bug, review

#259 avoid repeated deepcopy of descriptors during identification
  colcon_core/package_identification/__init__.py
Labels: enhancement, review

#261 fix command to remove trailing separator
  colcon_core/shell/sh.py
Labels: bug, review

#258 More Pythonic EventReactor
  colcon_core/event_reactor.py
  colcon_core/executor/__init__.py
  test/test_event_reactor.py
  test/test_executor.py
Labels: review
