Repository colcon/colcon-core, pull requests merged in 2020-03, with the labels that each got.

#313 improve performance deepcopying DependencyDescriptors
  colcon_core/dependency_descriptor.py
Labels: enhancement

#311 Make colcon list even fasterer
  colcon_core/package_descriptor.py
  test/test_package_descriptor.py
Labels: enhancement

#315 shorten prog to basename if on PATH
  colcon_core/command.py
Labels: enhancement

#317 Fix crash in has_test_dependency
  colcon_core/task/python/test/__init__.py
Labels: bug

#319 Generate xunit files valid for the junit10.xsd
  colcon_core/task/python/test/pytest.py
Labels: enhancement

#318 add flag to query non-recursive parser argument destinations
  colcon_core/argument_parser/__init__.py
  colcon_core/argument_parser/destination_collector.py
  test/spell_check.words
  test/test_destination_collector.py
Labels: enhancement

#320 support non-numeric log-level defaults
  colcon_core/command.py
Labels: enhancement

#327 Help text nudge to read the friendly manual
  colcon_core/command.py
Labels: enhancement

#328 add note to help message that stdout might not be shown by default
  colcon_core/task/python/test/pytest.py
  colcon_core/task/python/test/setuppy_test.py
Labels: enhancement

#331 print python coverage results to console
  colcon_core/task/python/test/pytest.py
Labels: enhancement

#326 add JobUnselected event to the build verb
  colcon_core/event/job.py
  colcon_core/executor/__init__.py
  colcon_core/verb/build.py
  test/test_executor.py
Labels: enhancement

#235 rename rc -> completed
  colcon_core/subprocess.py
  colcon_core/task/__init__.py
  colcon_core/task/python/build.py
  colcon_core/task/python/test/pytest.py
  colcon_core/task/python/test/setuppy_test.py
Labels: review

#332 add unwrap_default_value function
  colcon_core/argument_default.py
  test/test_argument_default.py
Labels: enhancement
